apiVersion: apps/v1
kind: Deployment
metadata:
  name: cit270ganyoraphaelservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cit270ganyoraphaelservice
  template:
    metadata:
      name: cit270ganyoraphaelservice
      labels:
        app: cit270ganyoraphaelservice
    spec:
      containers:
      - name: cit270ganyoraphaelservice
        image: gcr.io/cit-270-kubernetes/ganyoraphael-api
        volumeMounts:
        - name: ssl
          monutPath: "/etc/letsencrypt/live/ganyoraphael.cit270.com/"
        command: ["npm"]
        args: ["run", "starts"]
        resources:
          requests:
            cpu: 0.125
            memory: 500Mi
          limits:
            cpu: 0.125
            memory: 600Mi
        imagePullPolicy: Always
      volumes:
      - name: ssl
        secret:
          secretName: ganyoraphaelcerts


