apiVersion: apps/v1
kind: Deployment
metadata:
  name: citraphaelservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citraphaelservice
  template:
    metadata:
      name: citraphaelservice
      labels:
        app: citraphaelservice
    spec:
      containers:
      - name: citraphaelservice
        image: gcr.io/cit-270-kubernetes/raphael-api
        volumeMounts:
        - name: ssl
          monutPath: "/etc/letsencrypt/live/raphael.262.com/"
        command: ["npm"]
        args: ["run", "starts"]
        resources:
          requests:
            cpu: 0.125
            memory: 500Mi
          limits:
            cpu: 0.125
            memory: 600Mi
        imagePullPolicy: Always
      volumes:
      - name: ssl
        secret:
          secretName: raphaelcerts


